language: ruby
sudo: false
cache:
  directories:
  - vendor/bundle
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
bundler_args: --without development
before_install:
  -  gem update --system 2.1.11
script:
  - bundle exec rake syntax
  - bundle exec rake lint
  - bundle exec rake ci:setup:rspec spec
notifications:
  email:
    - biemond@gmail.com
env:
  - PUPPET_VERSION=3.7.4
  - PUPPET_VERSION=3.8.2
  - PUPPET_VERSION=4.2.2
  - PUPPET_VERSION=4.4.1

matrix:
  exclude:
    - rvm: 2.2.5
      env: PUPPET_VERSION=3.7.4
    - rvm: 2.3.1
      env: PUPPET_VERSION=3.7.4
    - rvm: 2.2.5
      env: PUPPET_VERSION=3.8.2
    - rvm: 2.3.1
      env: PUPPET_VERSION=3.8.2